blog/blog/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

import search_app

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('search/', include('search_app.urls'))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'  # Define the namespace for the app
urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.product_list, name='product_list'),
    path('<int:pk>/', views.product_detail, name='product_detail'),
    path('edit/<int:pk>/', views.edit, name='edit'),
    path('del/<int:pk>/', views.delete, name='delete'),
]

blog/search_app/urls.py
from django.urls import path
from .import views
app_name = 'search_app'
urlpatterns = [
    path('search/', views.SearchResult, name='SearchResult'),
]

blog/blogapp/models.py
from django.db import models

# Create your models here.
# creating  a database with name Product and name, desc etc are columns
class Product(models.Model):
    name = models.CharField(max_length=250,unique=True)
    desc = models.TextField(blank=True)
    img = models.ImageField(upload_to='gallery')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    def edit(self, name, desc, img):
        self.name = name
        self.desc = desc
        self.img = img
        self.save()

    def short_description(self):
        # split the description in to words
        words = self.desc.split()
        if len(words) > 50:
        # Join the first 50 words and add "..." at the end
            return ''.join(words[:30]) + '...'
        else:
            return self.desc

blog/search_app/models.py
from django.db import models

# Create your models here.

blog/blogapp/views.py
from django.core.paginator import Paginator, EmptyPage, InvalidPage
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from .models import Product  # importing the DB Product from models.py
from . form import ProductForm  # importing the form ProductForm from form.py

# Create your views here.
def product_list(request):
    products = Product.objects.all()

    paginator = Paginator(products, 6)
    try:
        page = int(request.GET.get('page', '1'))
    except:
        page = 1
    try:
        products = paginator.page(page)
    except (EmptyPage, InvalidPage):
        products = paginator.page(paginator.num_pages)

    return render(request, 'index.html', {'products': products})
def product_detail(request,pk):
    products = Product.objects.get(pk=pk)
    return render(request, 'index2.html', {'product': products})
def edit(request, pk):
    # Retrieve the product with the given primary key (pk), If the product does not exist, it returns a 404 error page.
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        # If the request method is POST (i.e., form submission),
        # Creates a ProductForm instance with the submitted data and the existing product (instance=product).
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()          # If valid, saves the changes to the product and
            return redirect('blogapp:product_list')        # redirects to the product list page.
    else:
        form = ProductForm(instance=product)
    return render(request, 'edit.html', {'form': form})


def delete(request,pk):
    product = get_object_or_404(Product, pk=pk)
    if request.method == 'POST':
        product.delete()
        return redirect('blogapp:product_list')
    return render(request, 'delete.html', {'product': product})

def home(request):
    return HttpResponse('Hello welcome to my Blog')

blog/search_app/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.db.models import Q
from django.shortcuts import render
from blogapp.models import Product
# Create your views here.


# Create your views here.
def SearchResult(request):
    query = request.GET.get('q')

    if query and query.strip():
        products = Product.objects.filter(Q(name__icontains=query) | Q(desc__icontains=query))
        return render(request, 'search.html', {'query': query, 'products': products})

    return render(request, 'index.html', {'query': query})

blog/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Idukki Blog</title>
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
     <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>

<div>
{%  include 'nav.html' %}
{%  block content %}
{% endblock %}
    </div>
</body>
</html>

blog/templates/delete.html
{% extends 'base.html' %}
{% block content %}
<h2> Delete Blog Post </h2>

<p>Are you sure you want to delete "{{ product.name }}"? </p>  <!--product - is the key in delete fn(views)-->
<form method="POST">
    {% csrf_token %}
    <button type="submit"> Delete </button>
</form>
{% endblock %}

blog/templates/details.html
{% extends 'base.html' %}
{% block content %}
<h1> {{product.name}}</h1>
<img src="{{product.img.url}}" alt="{{product.name}}">
<p>{{ product.desc}}</p>
{% endblock %}

blog/templates/edit.html
{% extends 'base.html' %}
{% block content %}

<h2> Edit Blog Post </h2>
<form method="POST">
<!-- Including {% csrf_token %} in your forms is an important security measure to protect against CSRF attacks and-->
<!-- is recommended for all forms that perform actions such as submitting data, updating records, or deleting records in Django applications.-->
    {% csrf_token %}

<!-- This template variable renders the form fields using the as_p method,
which formats the form fields as paragraphs (<p> elements).-->
<!-- Each form field is displayed with a label and an input field.-->
    {{ form.as_p }}
    <button type="submit"> Save Changes </button>
</form>
{% endblock %}

blog/templates/index.html
{% extends 'base.html' %}
{% block content %}

    <div class="container mt-5">
        <h2>Discover The Most Amazing Tourist Places In Idukki</h2> <br>
        <div class="row">
<!--  Taking the products from product_list(views) -->
            {% for product in products %}
                <div class="col-md-4 mb-4" >
                    <div class="card h-100">
                        <a href="{% url 'blogapp:product_detail' product.pk %}">
                            <img src="{{ product.img.url }}" alt="{{ product.created_name }}" class="card-img-top">
                        </a>
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.short_description }}</p>
                            <a href="{% url 'blogapp:edit' product.pk %}">Edit</a>
                            <a href="{% url 'blogapp:delete' product.pk %}">Delete</a> <br>
                            <small class="card-text">Created at: {{ product.created_at }}</small> <br>
                            <small class="card-text">Updated at: {{ product.updated_at }}</small>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>

  <!-- Pagination links -->

 <div class="mx-auto">
      {% if products.paginator.num_pages > 1 %}
      <hr>
      <div class="text-center">
          {% for pg in products.paginator.page_range %}
          <a href="?page={{pg}}" class="btn btn-light btn-sm {% if products.number == pg %} active {% endif %}">{{pg}}</a>
      {% endfor %}
      </div>
    {% endif %}
  </div>
    </div>
<!-- Add Bootstrap JS and jQuery scripts here (if needed) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
{% endblock %}

blog/templates/index2.html
{% extends 'base.html' %}
{% block content %}

<!--product is from the product_detail(views)-->
<br>
<h1> {{ product.name}} </h1><br>
<div>
    <img src="{{product.img.url}}" alt="{{product.name}}" width="400">
</div>
<br>
<p>{{ product.desc }}</p>
<a href="{% url 'blogapp:edit' product.pk %}"> Edit</a>
<a href="{% url 'blogapp:delete' product.pk %}"> Delete</a> <br>
<a href="{% url 'blogapp:product_list' %}"> Home </a>

{% endblock %}

blog/templates/nav.html
<!--Nav bar-->
        <nav class="navbar navbar-light" style="background-color: #5f9ea0 ;">
            <a class="navbar-brand">Misty Idukki</a>
               <form action="{% url 'search_app:SearchResult' %}" method="get">
                    <input type="text" name="q" placeholder="Search...">
                    <button type="submit">Search</button>
                </form>
        </nav>

blog/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
Search
{% endblock %}
{% block content %}
<div>
    <p class="text-center my_search_text">You have searched for:<b> "{{query}}"</b></p>
</div>
    <div class="container mt-5">
        <div class="row">
<!--  Taking the products from product_list(views) -->
            {% for product in products %}
                <div class="col-md-4 mb-4" >
                    <div class="card h-100">
                        {% if product.img %}
                        <a href="{% url 'blogapp:product_detail' product.pk %}">
                            <img src="{{ product.img.url }}" alt="{{ product.created_name }}" class="card-img-top">
                        </a>
                        {% endif %}
                        <div class="card-body">
                            <h5 class="card-title">{{ product.name }}</h5>
                            <p class="card-text">{{ product.desc }}</p>
<!--                            <p class="card-text">{{ product.short_description }}</p>-->
                        </div>
                    </div>
                </div>
            {% empty %}
            <div class="row mx-auto">
            <p class="text-center my_search_text">0 results found</p>
        </div>
            {% endfor %}
         </div>
    </div>
{% endblock %}